---
title: "Lesson 5 - Data Frames I"
author: "Aarushi Gupta SID 905-328-941"
date: "Stats 20 Section 1"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
    toc_depth: 3
---

## 1A

```{r 1A}
library(haven)
RN08_CNTY_data <- read_sav("RN08_CNTY_data.sav")
dim(RN08_CNTY_data)
A.1 <- RN08_CNTY_data[,c("AGE_GP","RACE_GP","PREP_SUM_PUF","MAR_CHLD","TOTSAL","TOTRNHRS_YR")]
A.1
```


## 1B

```{r 1B}
library(haven)
B.1 <- read_dta("us_counties.dta")
dim(B.1)
names(B.1)
summary(B.1[,c("cases","deaths")])
```

## 1C

```{r 1C}
library(haven)
C.1 <- read_sas("us_states.sas7bdat", NULL)
dim(C.1)
summary(C.1[,c("deaths")])
```


## 1D

```{r 1D}
library(readr)
D.1 <- read_tsv("https://www.gbcnv.edu/bookstore/2020-Fall.txt", col_names = FALSE)
D.1[,c(1,5,9,12,13)] <- NULL
dim(D.1)
```


## 2A

```{r 2A}
load(url("http://www.stat.ucla.edu/~vlew/datasets/ucpay2017.RData"))
head(uclaPayroll2017)
```

## 2B

```{r 2B}
save(A.1, B.1, C.1, D.1, file = "Lesson05Data.RData")
```
