---
title: "Lesson 8 - Base R Graphics"
author: "Aarushi Gupta SID 905-328-941"
date: "Stats 20 Section 1"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r}
library(haven)
library(readr)
library(dplyr)
library(ggplot2)
```

## 1 Line Graph with Multiple Lines and Legend

```{r fig.width = 10, fig.height = 8}
load(file = "ST3Covid19.rdata")
plot(CA$dailydeaths ~ CA$date, type = "l", col = "green", lwd = 2, 
     xlab = "Month", ylab = "daily deaths", main = "Covid-19 Daily Deaths")
lines(FL$dailydeaths ~ FL$date, col = "violet", lwd = 2)
lines(TX$dailydeaths ~ TX$date, col = "cyan", lwd= 2)
legend(x = "topleft", legend = c("CA", "FL", "TX"), 
       col = c("green", "violet", "cyan"), lwd = 2)
```


## 2 Boxplots 

```{r fig.width = 12, fig.height = 9}
DIS <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/DISNEY.csv")
PYPL <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/PAYPAL.csv")
boxplot(DIS$`Adj Close` ~ DIS$YM, col = "cyan", 
        xlab = "Year-Month", ylab = "Adjusted Closing Price", 
        main = "Boxplot Example - Stock Price 7/19 - 6/20", 
        cex.axis = 0.8, cex.main = 1.3, ylim = c(80, 180))
boxplot(PYPL$`Adj Close` ~ PYPL$YM, col = "yellow", 
        add = TRUE, at = 1:12 + 0.5, cex.axis = 0.8, ylim = c(80, 180))
legend(x = "bottom", legend = c("Disney", "Paypal"), 
       col = "black", pt.bg = c("cyan", "yellow"), pch = 22)
```

## 3 Histograms of Yelp Ratings

```{r fig.width = 7, fig.height = 9}
yelp3 <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/yelp3.csv")
par(mfrow = c(3,1))
hist(yelp3$stars[yelp3$categories.0 == "Vegan"], prob = TRUE, 
     col = "orange", xlab = "Yelp Rating", main = "Vegan Ratings", 
     cex.main = 1.4, xlim = c(1, 5))
hist(yelp3$stars[yelp3$categories.0 == "Buffets"], prob = TRUE, 
     col = "blue", xlab = "Yelp Rating", main = "Buffet Ratings", 
     cex.main = 1.4, xlim = c(1, 5))
hist(yelp3$stars[yelp3$categories.0 == "Sports Bars"], prob = TRUE, 
     col = "maroon", xlab = "Yelp Rating", main = "Sports Bar Ratings", 
     cex.main = 1.4, xlim = c(1, 5))
```


## 4A Scatterplot Matrix

```{r fig.width = 10, fig.height = 10}
plot(x = midwest[, c(5, 10, 18:20, 23)], 
     main = "Scatterplot Matrix of ggplot Dataset midwest",
     col = "blue", pch = 20)
```

## 4B Scatterplot with lines for means, different colors, legend

```{r fig.width = 9, fig.height = 6}
plot(midwest$percollege ~ midwest$perchsd, col = factor(midwest$state), 
     xlab = "perchsd", ylab = "percollege", 
     main = "Plot of College Degree on High School Diploma With Medians Drawn", 
     pch = 20, cex = 0.5)
abline(h = median(midwest$percollege), v = median(midwest$perchsd), col = c("red", "blue"))
legend(x = "topleft", legend = c("IL", "IN", "MI", "OH", "WI"), 
       col = c("black", "red", "green", "blue", "turquoise"), pch = 20)
```

## 4C Scatterplot with Regression line

```{r 4C}
plot(midwest$percprof ~ midwest$percollege, 
     xlab = "percollege", ylab = "percprof", 
     main = "Plot of Professionals on Percent College Degree With Regression Line", 
     col = "blue", pch = 20, cex = 0.5)
abline(lm(midwest$percprof ~ midwest$percollege), col = "red", lwd = 2)
```

## 5A Two barplots

```{r fig.width = 14, fig.height = 5}
par(mfrow = c(1,2))
DIA_CUT <- table(diamonds$cut)
barplot(DIA_CUT, col = c("red", "orange", "yellow", "green", "cyan"))
DIA_COL <- table(diamonds$color)
barplot(DIA_COL, col = c("white", "bisque", "yellow", "green", "cyan", "violet", "gray"))
```

## 5B Stacked Barplot

```{r fig.width = 7, fig.height = 8}
DIA_CUT_COL <- table(diamonds$cut, diamonds$color)
barplot(DIA_CUT_COL, col = c("red", "yellow", "green", "orange", "purple"), 
        ylim = c(0, 12000))
```

## 5C Percent Stacked Barplot

```{r 5C}
PDIA_CUT_COL <- prop.table(DIA_CUT_COL, margin = 2)
barplot(PDIA_CUT_COL, col = c("red", "yellow", "green", "orange", "purple"))
```

## 5D Grouped Barplot

```{r 5D}
barplot(DIA_CUT_COL, col = c("red", "orange", "yellow", "green", "cyan"), beside = TRUE)
```
